### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by VictorLessa** [mcdallas/wallstreet#24]
Traceback (most recent call last):
  File ".\main.py", line 6, in <module>
    from wallstreet import Stock, Call, Put
  File "C:\Users\Vlessa.terceiro\.windows-build-tools\python27\lib\site-packages\wallstreet\__init__.py", line 1, in <module>
    from wallstreet.wallstreet import Stock, Call, Put
  File "C:\Users\Vlessa.terceiro\.windows-build-tools\python27\lib\site-packages\wallstreet\wallstreet.py", line 92
    params = {'period1': datefrom, 'period2': dateto, 'interval': f'1{self.frequency}', 'events': 'history', 'crumb': self.crumb}

run code :

```py
from wallstreet import Stock, Call, Put
s = Stock('AAPL')
```

**Comment by mcdallas** [comment]
yes Python 2 is not supported
