### ISSUE TITLE
Error raised by query2.finance.yahoo.com

### ISSUE THREAD

**Issue by seranki** [mcdallas/wallstreet#32]
This example was working a couple of days ago. Today it is raising an error.

>>> from wallstreet import Stock, Call, Put  
>>> s = Stock('AAPL')  
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/site-packages/wallstreet/wallstreet.py", line 112, in __init__  
    self._yahoo(quote, exchange)  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/site-packages/wallstreet/wallstreet.py", line 126, in _yahoo  
    r.raise_for_status()  
  File "/Volumes/Backup/Users/......./anaconda3/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status  
    raise HTTPError(http_error_msg, response=self)  
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://query2.finance.yahoo.com/v7/finance/options/AAPL  
>>>

**Comment by mcdallas** [comment]
Looks like they now block non-browser user agents. #31 should fix this. Try reinstalling the newer version

**Comment by seranki** [comment]
Thanks for the rapid fix.
'pip uninstall' followed by 'pip install' updated wallstreet to v 0.3.1
The python script that uses wallstreet is now working again
