### ISSUE TITLE
error importing wallstreet package

### ISSUE THREAD

**Issue by lhenry7** [mcdallas/wallstreet#35]
Here is the error from simply importing. The 'pip install wallstreet' worked just fine.

PS C:\Users\larry\OneDrive\Documents\PythonProjects\options> python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from wallstreet import Stock, Call, Put
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\larry\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\wallstreet\__init__.py", line 1, in <module>
    from wallstreet.wallstreet import Stock, Call, Put
  File "C:\Users\larry\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\wallstreet\wallstreet.py", line 10, in <module>
    from wallstreet.blackandscholes import riskfree, BlackandScholes
  File "C:\Users\larry\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\wallstreet\blackandscholes.py", line 4, in <module>        
    from scipy.interpolate import interp1d
  File "C:\Users\larry\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\larry\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by lhenry7** [comment]
I upgraded python from 3.7.1 to 3.9.6 on Win10 seems to have resolved my issue.
